# -*- coding: utf-8 -*-
"""yolov8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aM7yZbyrOsBeLlv6xJ_0Y2Zdws-7zfzz
"""

!pip install ultralytics

from ultralytics import YOLO

"""Custom Data Training


"""

!yolo task=detect mode=train model=yolov8l.pt data=../content/drive/MyDrive/dataset/Satelliteimagery/data.yaml epochs=20 imgsz=640